### Get all blog posts
GET http://localhost:3003/api/blogs

### Create blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZDI1MTJjYTFlYTEzZDg5YmZjNTFmMSIsImlhdCI6MTY3NDgwMTMwNn0.YcszKHy77SlGq518exWl_iSDiMBdaIGvHA5a13cd66c

{
  "title": "third post",
  "author": "second Author",
  "url": "jee",
  "likes": 0,
  "userId": "63d2512ca1ea13d89bfc51f1"
}

### Delete blog post
DELETE http://localhost:3003/api/blogs/63cf9844381a89c024319d37

### Update blog post
PATCH http://localhost:3003/api/blogs/63ca66bb5a43c58c15294446
Content-Type: application/json

{
  "title": ""
}

### Add user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "be",
  "name": "Benjamin Testaaja",
  "password": "ben"
}

### Get users
GET http://localhost:3003/api/users

### Login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "ben",
  "password": "ben"
}